name: husarion-rplidar
adopt-info: husarion-rplidar
license: Apache-2.0
summary: The husarion-rplidar
description: |
  The husarion-rplidar snap contains all the necessary software to bring the RPLIDAR laser sensors up.
  It offers the following parameters:

    Key                 Default Value
    driver              {...}
    ros-domain-id       0
    ros-localhost-only  0
    transport           udp
    serial-port         auto
    serial-baudrate     256000
    
  The driver parameter is a dictionary that contains the following keys:

    Key                            Default Value
    driver.device-namespace        (unset)
    driver.namespace               (unset)
    driver.scan-mode               (unset)
    driver.channel-type            serial
    driver.frame-id                laser
    driver.inverted                false
    driver.angle-compensate        true

  To set the parameters, use the snap set command, e.g.,

    snap set husarion-rplidar driver.namespace=robot

grade: stable
confinement: strict
base: core22

contact: https://github.com/husarion/husarion-rplidar-snap/issues
issues: https://github.com/husarion/husarion-rplidar-snap/issues
website: https://husarion.com/

architectures:
  - build-on: amd64
    build-for: amd64
  # - build-on: amd64
  #   build-for: arm64
  - build-on: arm64
    build-for: arm64

slots:
  shm-slot:
    interface: shared-memory
    write: ['*'] # paths are relative to /dev/shm

plugs:
  shm-plug:
    interface: shared-memory
    shared-memory: shm-slot
    private: false

apps:

  daemon:
    command: usr/bin/launcher.sh
    command-chain: [usr/bin/ros_setup.sh]
    daemon: simple
    install-mode: enable
    stop-mode: sigint-all
    plugs: [network, network-bind, shm-plug, raw-usb]
    slots: [shm-slot]
    extensions: [ros2-humble-ros-base]

  husarion-rplidar:
    command: usr/bin/launcher.sh
    command-chain: [usr/bin/check_daemon_running.sh, usr/bin/ros_setup.sh]
    plugs: [network, network-bind, shm-plug, raw-usb]
    slots: [shm-slot]
    extensions: [ros2-humble-ros-base]

  start:
    command: usr/bin/start_launcher.sh

  stop:
    command: usr/bin/stop_launcher.sh

parts:
  husarion-rplidar:
    plugin: nil
    stage-packages:
      - ros-humble-rplidar-ros
      - usbutils # lsusb
    override-stage: |
      craftctl default
      version="$(apt-cache policy ros-humble-rplidar-ros | grep Candidate | awk '{print $2}')"
      craftctl set version="$version"
      craftctl set grade="stable"
      
  # copy local scripts to the snap usr/bin
  local-files-ros:
    plugin: dump
    source: snap/local/ros_common/
    organize:
      '*.sh': usr/bin/
      '*.xml': usr/share/husarion-rplidar/config/

  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/
      '*.py': usr/bin/
      # '*.yaml': usr/share/husarion-rplidar/config/
      # '*.xml': usr/share/husarion-rplidar/config/
      # '*.json': usr/share/husarion-rplidar/config/
