name: husarion-rplidar
adopt-info: husarion-rplidar
license: Apache-2.0
summary: RPLIDAR ROS 2 driver for Husarion robots
icon: snap/gui/icon.png
description: |
  The `husarion-rplidar` snap contains all the necessary software to bring the RPLIDAR LIDARS up.
  
  **Parameters**

  The snap provides the following configurable parameters (`param name`: `default value`):

  * `configuratin`: `custom`
  * `driver`: `{...}`
  * `ros`: `{...}`

  The `ros` contains the following keys:

  * `ros.domain-id`: `0` - Sets the `ROS_DOMAIN_ID` environment variable for the ROS driver.
  * `ros.localhost-only`: `0` - Sets the `ROS_LOCALHOST_ONLY` environment variable for the ROS driver.
  * `ros.transport`: `udp` - Configures DDS transport. Options are `udp`, `shm`, `builtin` (or `rmw_fastrtps_cpp`), `rmw_cyclonedds_cpp`. Corresponding DDS XML files can be found in the `/var/snap/rosbot-xl/common` directory (custom FastDDS setups can also be created here).
  * `ros.namespace`: `(unset)` - Namespace for all topics and transforms.

  The `driver` contains the following keys:

  * `channel-type`: `serial`
  * `serial-port`: `auto`
  * `serial-baudrate`: `256000`
  * `frame-id`: `laser`
  * `inverted`: `false`
  * `angle-compensate`: `true`
  * `scan-mode`: `(unset)`
  * `device-namespace`: `(unset)`

  To set the parameters, use the snap set command, e.g.,

     snap set husarion-rplidar driver.device-namespace=front_lidar

grade: stable
confinement: strict
base: core22

contact: https://github.com/husarion/husarion-rplidar-snap/issues
issues: https://github.com/husarion/husarion-rplidar-snap/issues
website: https://husarion.com/

architectures:
  - build-on: amd64
    build-for: amd64
  # - build-on: amd64
  #   build-for: arm64
  - build-on: arm64
    build-for: arm64

slots:
  shm-slot:
    interface: shared-memory
    write: ['*'] # paths are relative to /dev/shm

plugs:
  shm-plug:
    interface: shared-memory
    shared-memory: shm-slot
    private: false

apps:

  daemon:
    command: usr/bin/launcher.sh
    command-chain: [usr/bin/ros_setup.sh]
    daemon: simple
    install-mode: enable
    plugs: [network, network-bind, shm-plug, raw-usb]
    slots: [shm-slot]
    extensions: [ros2-humble-ros-base]

  husarion-rplidar:
    command: usr/bin/launcher.sh
    command-chain: [usr/bin/check_daemon_running.sh, usr/bin/ros_setup.sh]
    plugs: [network, network-bind, shm-plug, raw-usb]
    slots: [shm-slot]
    extensions: [ros2-humble-ros-base]

  start:
    command: usr/bin/start_launcher.sh

  stop:
    command: usr/bin/stop_launcher.sh

parts:
  husarion-rplidar:
    plugin: nil
    stage-packages:
      - ros-humble-rplidar-ros
    override-stage: |
      craftctl default
      version="$(apt-cache policy ros-humble-rplidar-ros | grep Candidate | awk '{print $2}')"
      craftctl set version="$version"
      craftctl set grade="stable"

  yq:
    plugin: nil
    override-build: |
      craftctl default

      YQ_VERSION="v4.35.1"
      TARGETARCH=$CRAFT_ARCH_BUILD_FOR
      curl -L "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${TARGETARCH}" -o $CRAFT_PART_BUILD/yq
    override-prime: |
      craftctl default
    
      cp $CRAFT_PART_BUILD/yq $CRAFT_PRIME/usr/bin/yq
      chmod +x $CRAFT_PRIME/usr/bin/yq
    build-packages:
      - curl

  # copy local scripts to the snap usr/bin
  local-files-ros:
    plugin: dump
    source: snap/local/local-ros/
    organize:
      '*.sh': usr/bin/
      '*.xml': usr/share/husarion-rplidar/config/

  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/
      '*.py': usr/bin/
      # '*.yaml': usr/share/husarion-rplidar/config/
      # '*.xml': usr/share/husarion-rplidar/config/
      # '*.json': usr/share/husarion-rplidar/config/