#!/bin/bash -e

# Define a function to log and echo messages
source $SNAP/usr/bin/utils.sh

$SNAP/usr/bin/install_hook_ros.sh

# Parameters are 'unset'.
# Default configuration values is left to the launch file.
snapctl set configuration="custom"

snapctl set driver.channel-type="serial"
snapctl set driver.serial-port="auto"
snapctl set driver.serial-baudrate="256000"
snapctl set driver.frame-id="laser"
snapctl set driver.inverted="false"
snapctl set driver.angle-compensate="true"
snapctl set driver.scan-mode!
snapctl set driver.device-namespace!

if ! snapctl is-connected raw-usb; then
  log "Plug 'raw-usb' isn't connected, please run:"
  log "sudo snap connect ${SNAP_NAME}:raw-usb"
fi

# # copy meshes to shared folder
# log "copy meshes to '${SNAP_COMMON}/ros2_ws/'"
# mkdir -p ${SNAP_COMMON}/ros2_ws
# cp -r $SNAP/opt/ros/snap/share/rosbot_xl_description ${SNAP_COMMON}/ros2_ws/rosbot_xl_description
# cp -r $SNAP/opt/ros/snap/share/ros_components_description ${SNAP_COMMON}/ros2_ws/ros_components_description
